-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgp3SxFjJ4TtvhVgy9
MBDRBnBrSgtkPLoKQFK5p+3dU6ugCgYIKoZIzj0DAQehRANCAARsOUJBCAqru8MG
fWYJPmxfcyHox55bgQFwE9jMQi2BhMJTmt5KPrtjpyWcYoBvLrTeqiR3gKhyEC9Q
Nv2lpurG
-----END PRIVATE KEY-----